apiVersion: v1
kind: Namespace
metadata:
  name: taskmgr

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: taskmgr
type: Opaque
data:
  DATABASE_URL: <BASE64_ENCODED_DATABASE_URL>
